// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmnRNunjiYZ8qV2fQq1Ho2NwwIPUmO09E',
    appId: '1:687897477415:web:18d575142a0fa64a4b6902',
    messagingSenderId: '687897477415',
    projectId: 'aquariumapp-707aa',
    authDomain: 'aquariumapp-707aa.firebaseapp.com',
    storageBucket: 'aquariumapp-707aa.firebasestorage.app',
    measurementId: 'G-PGYZS9CBCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9vtMS_mwWgwQDhy8ygF1O2EgvD6QfX0',
    appId: '1:687897477415:android:09842ff013b37acc4b6902',
    messagingSenderId: '687897477415',
    projectId: 'aquariumapp-707aa',
    storageBucket: 'aquariumapp-707aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEq9J7ebCkP4PFa4w3eWmKEw4RYgTXiUQ',
    appId: '1:687897477415:ios:3a74811a733ee5c34b6902',
    messagingSenderId: '687897477415',
    projectId: 'aquariumapp-707aa',
    storageBucket: 'aquariumapp-707aa.firebasestorage.app',
    iosBundleId: 'com.example.screenTimeTrackerWithAquarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEq9J7ebCkP4PFa4w3eWmKEw4RYgTXiUQ',
    appId: '1:687897477415:ios:3a74811a733ee5c34b6902',
    messagingSenderId: '687897477415',
    projectId: 'aquariumapp-707aa',
    storageBucket: 'aquariumapp-707aa.firebasestorage.app',
    iosBundleId: 'com.example.screenTimeTrackerWithAquarium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmnRNunjiYZ8qV2fQq1Ho2NwwIPUmO09E',
    appId: '1:687897477415:web:7e9e9034ddaa83a74b6902',
    messagingSenderId: '687897477415',
    projectId: 'aquariumapp-707aa',
    authDomain: 'aquariumapp-707aa.firebaseapp.com',
    storageBucket: 'aquariumapp-707aa.firebasestorage.app',
    measurementId: 'G-B3V154128N',
  );
}
